// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqwvuuaeqtesnamfelfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdxd3Z1dWFlcXRlc25hbWZlbGZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTYwNTQsImV4cCI6MjA2MTE3MjA1NH0.wNH-1_p2FC88Dy8E-oK4ivCGPqYuMGfpMFhBJQXNg1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);